### PR TITLE
Fixed non_unique hashed_index iteration problem.

### PR DESCRIPTION
**Pull request by redboltz**
See https://github.com/ruediger/Boost-Pretty-Printer/pull/36#issuecomment-408771413

### CODE REVIEW

**Comment by redboltz** [comment]
https://www.slideshare.net/taka111/boostmultiindex-version-1660-internal-structure-and-iteration-algorithm-for-gdb-boostprerryprinter

I wrote a slide that describes the iteration algorithm of this pull request.

**Comment by redboltz** [comment]
`s/cur/crt/ ` the last slide.

**Comment by redboltz** [comment]
I moved the slide to speakerdeck. I found some typos but slideshare doesn't seems that re-upload the slide.

https://speakerdeck.com/redboltz/boost-multi-index-version-equals-1-dot-56-dot-0-internal-structure-and-iteration-algorithm-for-gdb-boost-prerry-printer

**Comment by redboltz** [comment]
NOTE: 

We cannot depend on **value comparison** during the iteration. Equality is application defined. So I use only pointers comparison.

**Comment by mbalabin** [comment]
@joaquintides Thanks for the help!

From my side, I can see at least, that the problematic case (non-unique keys) is covered by the test.

**Comment by redboltz** [comment]
@mbalabin , thank you for merging!

**Pull request merged**
